# Generated by Django 2.0.8 on 2018-08-03 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('precio_por_unidad', models.FloatField()),
                ('min_stock', models.IntegerField()),
                ('max_stock', models.IntegerField()),
                ('area', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=200)),
                ('fecha_de_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('conversiones', jsonfield.fields.JSONField()),
                ('notas', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Unidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
