# Generated by Django 2.0.8 on 2018-08-03 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('RFC', models.CharField(max_length=13)),
                ('sucursales', jsonfield.fields.JSONField()),
                ('calificacion', models.FloatField()),
                ('notas', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 8, 3, 15, 41, 5, 120412, tzinfo=utc))),
                ('proceso', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requisiciones',
            },
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='unidad',
            name='conversiones',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
