# Generated by Django 2.0.8 on 2018-08-11 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180803_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_por_unidad',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='calificacion',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sucursales',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 18, 57, 34, 481771, tzinfo=utc)),
        ),
    ]
