# Generated by Django 2.0.8 on 2018-08-18 20:36

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180811_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_por_unidad',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
