# Generated by Django 2.0.8 on 2018-08-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180818_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
