# Generated by Django 2.0.8 on 2018-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180818_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='bpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pa',
            field=models.BooleanField(default=False),
        ),
    ]
