# Generated by Django 2.0.8 on 2018-08-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180820_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre_corto',
            field=models.CharField(default='', max_length=60),
        ),
    ]
