# Generated by Django 2.0.8 on 2018-08-20 15:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_proveedor_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='b',
            field=models.BooleanField(default=False, verbose_name='Barra Jardín'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='bpa',
            field=models.BooleanField(default=False, verbose_name='Barra Planta Alta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='c',
            field=models.BooleanField(default=False, verbose_name='Cacomixtle'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pa',
            field=models.BooleanField(default=False, verbose_name='Planta Alta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sucursales',
            field=jsonfield.fields.JSONField(blank=True, verbose_name='Sucursales {id sucursal:ubicación}'),
        ),
    ]
