# Generated by Django 2.0.8 on 2018-08-20 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180820_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Listas',
            },
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='sucursales',
        ),
    ]
