# Generated by Django 2.0.8 on 2018-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180820_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='zona',
            field=models.CharField(default='La Cruz', max_length=120),
        ),
    ]
