# Generated by Django 2.0.8 on 2018-08-20 22:18

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_proveedor_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('otrocentro', jsonfield.fields.JSONField(blank=True)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Zona'),
        ),
    ]
