# Generated by Django 2.0.8 on 2018-08-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20180820_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='zona',
        ),
    ]
