# Generated by Django 2.0.8 on 2018-08-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_proveedor_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='zona_id',
            field=models.IntegerField(default=1),
        ),
    ]
