# Generated by Django 2.0.8 on 2018-08-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_zona_zona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Zona'),
        ),
    ]
