# Generated by Django 2.0.8 on 2018-08-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_proveedor_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
