# Generated by Django 2.0.8 on 2018-08-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_lista_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='zona_id',
        ),
    ]
