# Generated by Django 2.0.8 on 2018-08-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_remove_zona_zona_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='zona',
        ),
    ]
