# Generated by Django 2.0.8 on 2018-08-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_remove_proveedor_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
