# Generated by Django 2.0.8 on 2018-08-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_producto_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
