# Generated by Django 2.0.8 on 2018-08-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_lista_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lista',
            name='unidad',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lista',
            name='proveedor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lista',
            name='zona',
            field=models.CharField(default='', max_length=100),
        ),
    ]
