# Generated by Django 2.0.8 on 2018-09-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20180822_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='zona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='webapp.Zona'),
        ),
    ]
