# Generated by Django 2.0.8 on 2018-09-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20180901_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='zona',
        ),
    ]
