# Generated by Django 2.0.8 on 2018-09-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_remove_proveedor_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Zona'),
        ),
    ]
