# Generated by Django 2.0.8 on 2018-09-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_proveedor_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='zone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='webapp.Zona'),
        ),
    ]
