# Generated by Django 2.0.8 on 2018-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_auto_20180901_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_por_unidad',
            field=models.FloatField(),
        ),
    ]
