# Generated by Django 2.0.8 on 2018-09-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Area'),
        ),
    ]
