# Generated by Django 2.0.8 on 2018-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20180901_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nombre',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
