# Generated by Django 2.0.8 on 2018-09-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_area_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('precio_por_unidad', models.FloatField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Unidad')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='relacion_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.Insumo'),
        ),
    ]
